### ISSUE TITLE
Confirmation of alert box is not working

### ISSUE THREAD

**Issue by matsales28** [thoughtbot/capybara_accessibility_audit#8]
**Problem:**
When using the `accept_confirm` or `accept_alert` methods along with the `capybara_accessibility_audit` gem, a `Selenium::WebDriver::Error::UnexpectedAlertOpenError` error is raised during the test execution.

**Expected Behavior:**
The test should run without any errors when using the `accept_confirm` or `accept_alert` methods, even with the `capybara_accessibility_audit` gem enabled.

**Actual Behavior:**
The test is raising a `Selenium::WebDriver::Error::UnexpectedAlertOpenError` when using the `accept_confirm` or `accept_alert` methods with the `capybara_accessibility_audit` gem.

**Steps to Reproduce:**
I've created a [GitHub repository](https://github.com/matsales28/capybara-accessibility-accept-confirm-issue) that demonstrates the issue. The repository contains a simple system spec (`system/root_spec.rb`) utilising the `accept_confirm` method:

```ruby
require "rails_helper"

describe "Root" do
  around do |example|
    with_accessibility_audit_options skipping: %w[
    html-has-lang
    landmark-one-main
    page-has-heading-one
    region
    ] do
      example.run
    end
  end

  it "raises an error", js: true do
    visit root_path

    accept_confirm do
      click_on "Alert"
    end

    expect(page).to have_content("Root Show")
  end
end
```

**Comment by seanpdoyle** [comment]
@matsales28 thank you for opening this issue. Does https://github.com/thoughtbot/capybara_accessibility_audit/pull/9 fix the broken behavior?

**Comment by matsales28** [comment]
> @matsales28 thank you for opening this issue. Does #9 fix the broken behavior?

Yes, I just tested on the repo I used as a demonstration. It's working fine, thanks for fixing it!
